### ISSUE TITLE
Merge `penalty` and `regType` keywords?

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#13] opened 2020-08-07 22:19 UTC
In `snlls` and `fitsignal`, one can switch regularization on/off with the `penalty` keyword argument (True/False), and one can choose the type of regularization with the `regType` keyword argument. What about eliminating `penalty` and using `regType=None` in place of `penalty=False`? Seems like this would preserve functionality and simplify the interface.

**Comment by luisfabib** [comment] 2020-08-24 06:00
I see your point, I believe the problem is poor naming of the `penalty` option. The current behavior is the following: 

- `penalty=None`: whether to use a regularization penalty is determined automatically based on the condition number using the penalty specified in `regtype`. 

- `penalty=True/False`: Enforces the use of a penalty regardless of the condition number. If `True` it uses the penalty in `regtype`.

Both options cannot be simply merged by adding a `None` case for `regtype` since `penalty` has three cases (`None`,`True`,`False`). Maybe if we rename the option `penalty` into something like `forcepenalty` to strengthen the idea that it enforces a decision upon the automatic one if specified.

**Comment by stestoll** [comment] 2020-08-24 06:20
What is the use case for `penalty=None`?

Also, as you describe it, it should be `penalty=automatic` or similar. `None` is confusing.

**Comment by luisfabib** [comment] 2020-08-24 06:26
Agreed, it should be something like `penalty='auto'` for the automatic behavior and `penalty=True/False` for the manual switching.

**Comment by stestoll** [comment] 2020-08-25 07:50
Maybe `reg` instead of `penalty`, for consistency with `regType` etc?

**Closed** 2020-08-26 06:21 UTC
Labels: design
