### ISSUE TITLE
2D datasets

### ISSUE THREAD

**Issue by ecanarie** [JeschkeLab/DeerLab#30] opened 2020-09-17 21:42 UTC
Loading a 2D dataset would be neat. If I load a 2D dataset: 

````
t, V = dl.deerload('20200828_41R1_211R1_apoMBP_4PDEER_50K.DTA')
````

I get the following error: 

````
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-14-a93ba8068173> in <module>
----> 1 t, V = dl.deerload('20200828_41R1_211R1_apoMBP_4PDEER_50K.DTA')

~/Library/Python/3.8/lib/python/site-packages/deerlab/deerload.py in deerload(fullbasename, Scaling, plot, full_output, *args, **kwargs)
     46
     47     # Read descriptor file (contains key-value pairs)
---> 48     parameters = read_description_file(filename_dsc)
     49     parDESC = parameters["DESC"]
     50     parSPL = parameters["SPL"]

~/Library/Python/3.8/lib/python/site-packages/deerlab/deerload.py in read_description_file(DSCFileName)
   283     """
   284     with open(DSCFileName,"r") as f:
--> 285         allLines = f.readlines()
    286 
    287     # Remove lines with comments

/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 3426: invalid start byte
`````

**Comment by luisfabib** [comment] 2020-09-18 07:57
I have encountered this previously on Python. There might be some non-ASCII character in the DSC file that cannot be UTF-8 decoded. 

I know how to fix this, but I would require the data to be able to debug and test the fix. Can you please upload it or send it to me via email?

**Comment by luisfabib** [comment] 2020-09-18 13:53
I could not reproduce the error on my computer with your data. Still I just committed a potential fix for the bug. Please let me know if it fixed the error on your side.

**Comment by ecanarie** [comment] 2020-09-18 21:16
This commit solved the issue on my Mac. Thank you!

**Closed** 2020-09-18 23:08 UTC
Labels: bug
